### PR TITLE
Fixes and refactoring

### LINKED ISSUE #6: Use eslint-config-aftereffects
Thanks to @runegan for the heads up!

https://www.npmjs.com/package/eslint-config-aftereffects

### PR DESCRIPTION
**Pull request by runegan**
85ef5bf resolves #6

### CODE REVIEW

File: ae-ease-to-gsap-customease.jsx [hunk 1]
```diff
@@ -248,25 +248,15 @@
 		var endInterpolation = property.keyInInterpolationType(endIndex);
 
 		if (startInterpolation === KeyframeInterpolationType.LINEAR &&
-			endInterpolation === KeyframeInterpolationType.LINEAR) {
+			endInterpolation !== KeyframeInterpolationType.HOLD) {
```
Comment (Lange) [inline ae-ease-to-gsap-customease.jsx]: I don't think this is correct. This would cause a linear-bezier pair to be calculated as a linear-linear pair.

File: ae-ease-to-gsap-customease.jsx [hunk 2]
```diff
@@ -108,87 +108,75 @@
...
 		alert('Please Select at least one Property (Scale, Opacity, etc)');
 		return;
 	}
 
-	for (var i = 0; i < selectedLayers.length; i++) {
-		for (var f in selectedProperties) {
-			if (!{}.hasOwnProperty.call(selectedProperties, f)) {
-				continue;
-			}
+	for (var f = 0; f < selectedProperties.length; f++) {
```
Comment (Lange) [inline ae-ease-to-gsap-customease.jsx]: Very good catch! These few lines were left over from the copy-pasted code that was the base of this script, I totally didn't notice the problems here.

File: ae-ease-to-gsap-customease.jsx (hunk 1 above)
Comment (runegan) [reply ae-ease-to-gsap-customease.jsx]: My bad, I didn't read the return values properly, they looked the same at a glance, so I assumed they were.
I'll add a revert of this commit
